<?php

namespace App\Http\Controllers;

class ExcursionController extends Controller
{
    private function getData(): array
    {
        return [
            'canoe-lac-aheme' => [
                'slug'        => 'canoe-lac-aheme',
                'nom'         => 'Canoë sur le Lac Ahémé',
                'ville'       => 'Possotomé',
                'duree'       => '3 heures',
                'categorie'   => 'Nature & Eau',
                'hero_img'    => 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=1920',
                'galerie'     => [
                    'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800',
                    'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
                    'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=800',
                ],
                'description' => 'Partez à la découverte du lac Ahémé en canoë, l\'un des plus grands lacs du Bénin. Cette excursion vous emmène sur les eaux calmes du lac, où vous rencontrerez les pêcheurs locaux dans leurs pirogues traditionnelles, observerez la faune aquatique et admirerez les magnifiques reflets du soleil sur l\'eau.',
                'details'     => 'Idéale en début de matinée ou en fin d\'après-midi, cette sortie de 3 heures est parfaite pour tous les niveaux. Les canoës sont fournis et les guides locaux vous accompagnent tout au long du parcours. Les clients de l\'hôtel et du restaurant bénéficient du canoë gratuitement.',
                'inclus'      => ['Canoë et pagaies fournis', 'Guide local', 'Gilet de sauvetage', 'Gratuit pour clients hôtel'],
                'pratique'    => ['Niveau' => 'Tous niveaux', 'Départ' => 'Depuis Chez Théo', 'Groupe' => '2-8 personnes', 'Tenue' => 'Vêtements confortables'],
                'highlights'  => ['Rencontre avec les pêcheurs', 'Faune et flore lacustre', 'Coucher de soleil sur le lac', 'Canoë gratuit pour clients'],
                'icon'        => 'sailboat',
                'prev'        => null,
                'next'        => 'source-thermale',
            ],
            'source-thermale' => [
                'slug'        => 'source-thermale',
                'nom'         => 'Source Thermale',
                'ville'       => 'Possotomé',
                'duree'       => '1 heure',
                'categorie'   => 'Nature & Bien-être',
                'hero_img'    => 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=1920',
                'galerie'     => [
                    'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=800',
                    'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
                    'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
                ],
                'description' => 'Découvrez l\'origine de l\'eau thermale naturelle de Possotomé, jaillissant à 40°C depuis des sources ancestrales. Cette visite vous révèle les secrets géologiques et les vertus thérapeutiques reconnues de cette eau thermale unique au Bénin.',
                'details'     => 'La source thermale est accessible à pied depuis l\'hôtel. Un guide vous expliquera l\'histoire des sources, leur formation géologique et les usages traditionnels de l\'eau thermale par les habitants de Possotomé depuis des générations.',
                'inclus'      => ['Guide local', 'Explications historiques', 'Dégustation de l\'eau thermale', 'Accessible depuis l\'hôtel'],
                'pratique'    => ['Niveau' => 'Tous niveaux', 'Départ' => 'Depuis Chez Théo', 'Groupe' => 'Individuel ou groupe', 'Tenue' => 'Tenues légères'],
                'highlights'  => ['Eau à 40°C naturelle', 'Histoire géologique locale', 'Vertus thérapeutiques', 'Site ancestral'],
                'icon'        => 'flame',
                'prev'        => 'canoe-lac-aheme',
                'next'        => 'marche-poterie',
            ],
            'marche-poterie' => [
                'slug'        => 'marche-poterie',
                'nom'         => 'Marché International de Poterie',
                'ville'       => 'Sé',
                'duree'       => '½ journée',
                'categorie'   => 'Culture & Artisanat',
                'hero_img'    => 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1920',
                'galerie'     => [
                    'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800',
                    'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800',
                    'https://images.unsplash.com/photo-1520209759809-a9bcb6cb3241?w=800',
                ],
                'description' => 'Le marché de Sé est l\'un des plus grands marchés de poterie du Bénin. Chaque semaine, des centaines d\'artisans venus de toute la région y exposent leurs céramiques, terres cuites et objets traditionnels. Une immersion authentique dans l\'artisanat béninois.',
                'details'     => 'Situé à quelques kilomètres de Possotomé, le marché de Sé vous offre l\'opportunité de rencontrer directement les potiers et d\'acquérir des pièces uniques fabriquées à la main. Nos guides vous accompagnent et facilitent les échanges avec les artisans locaux.',
                'inclus'      => ['Transport depuis Chez Théo', 'Guide local', 'Négociation avec les artisans', 'Découverte des techniques'],
                'pratique'    => ['Niveau' => 'Tous niveaux', 'Départ' => 'Depuis Chez Théo', 'Groupe' => '2-10 personnes', 'Budget' => 'Prévoir pour achats'],
                'highlights'  => ['Artisans locaux', 'Poteries traditionnelles', 'Ambiance de marché africain', 'Souvenirs authentiques'],
                'icon'        => 'shopping-bag',
                'prev'        => 'source-thermale',
                'next'        => 'palais-royal-doutou',
            ],
            'palais-royal-doutou' => [
                'slug'        => 'palais-royal-doutou',
                'nom'         => 'Palais Royal',
                'ville'       => 'Doutou',
                'duree'       => '1 heure',
                'categorie'   => 'Histoire & Patrimoine',
                'hero_img'    => 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1920',
                'galerie'     => [
                    'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800',
                    'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800',
                    'https://images.unsplash.com/photo-1520209759809-a9bcb6cb3241?w=800',
                ],
                'description' => 'Visitez le Palais Royal de Doutou, témoin de l\'histoire du royaume du Dahomey et de ses traditions royales ancestrales. Ce site historique conserve l\'architecture et les symboles du pouvoir royal qui ont façonné la région pendant des siècles.',
                'details'     => 'Le Palais Royal de Doutou est gardien d\'une histoire millénaire. Accompagné d\'un guide local, vous découvrirez l\'architecture royale, les objets rituels et les récits des anciens rois qui ont régné sur ces terres avant la colonisation.',
                'inclus'      => ['Transport depuis Chez Théo', 'Guide local bilingue', 'Entrée au palais', 'Récits historiques'],
                'pratique'    => ['Niveau' => 'Tous niveaux', 'Départ' => 'Depuis Chez Théo', 'Distance' => 'Proche de Possotomé', 'Tenue' => 'Correcte requise'],
                'highlights'  => ['Architecture royale', 'Objets rituels ancestraux', 'Histoire du Dahomey', 'Guide passionné'],
                'icon'        => 'landmark',
                'prev'        => 'marche-poterie',
                'next'        => 'temple-pythons',
            ],
            'temple-pythons' => [
                'slug'        => 'temple-pythons',
                'nom'         => 'Temple des Pythons',
                'ville'       => 'Ouidah',
                'duree'       => '1 heure',
                'categorie'   => 'Culture & Vodoun',
                'hero_img'    => 'https://images.unsplash.com/photo-1520209759809-a9bcb6cb3241?w=1920',
                'galerie'     => [
                    'https://images.unsplash.com/photo-1520209759809-a9bcb6cb3241?w=800',
                    'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800',
                    'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
                ],
                'description' => 'Le Temple des Pythons de Ouidah est l\'un des lieux les plus emblématiques de la religion vodoun au Bénin. Des dizaines de pythons royaux sacrés y vivent en liberté, vénérés comme des êtres divins par les fidèles. Une expérience unique et envoûtante.',
                'details'     => 'Ouidah est la capitale spirituelle du vodoun. Au temple, vous pourrez observer et même toucher les pythons sacrés sous la supervision des gardiens. La visite inclut également des explications sur les rites et croyances vodoun, religion reconnue patrimoine culturel mondial.',
                'inclus'      => ['Transport depuis Chez Théo', 'Guide local', 'Entrée au temple', 'Explications sur le vodoun'],
                'pratique'    => ['Niveau' => 'Tous niveaux', 'Distance' => '45 min de Possotomé', 'Groupe' => '2-12 personnes', 'Note' => 'Respect des lieux requis'],
                'highlights'  => ['Pythons royaux sacrés', 'Religion vodoun authentique', 'Gardiens du temple', 'Atmosphère mystique'],
                'icon'        => 'zap',
                'prev'        => 'palais-royal-doutou',
                'next'        => 'musee-historique',
            ],
            'musee-historique' => [
                'slug'        => 'musee-historique',
                'nom'         => 'Musée Historique',
                'ville'       => 'Ouidah',
                'duree'       => '1 heure',
                'categorie'   => 'Histoire & Patrimoine',
                'hero_img'    => 'https://images.unsplash.com/photo-1575223970966-76ae61ee7838?w=1920',
                'galerie'     => [
                    'https://images.unsplash.com/photo-1575223970966-76ae61ee7838?w=800',
                    'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800',
                    'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800',
                ],
                'description' => 'Le Musée Historique de Ouidah retrace l\'histoire de la traite négrière, du royaume du Dahomey et du vodoun à travers une collection remarquable d\'objets, documents et œuvres d\'art. Un passage obligé pour comprendre l\'histoire du Bénin et de l\'Afrique de l\'Ouest.',
                'details'     => 'Installé dans l\'ancien fort portugais São João Baptista de Ajudá, le musée présente des collections qui couvrent la période précoloniale, la traite transatlantique et l\'époque coloniale. Un guide vous accompagnera à travers les différentes salles.',
                'inclus'      => ['Transport depuis Chez Théo', 'Guide local bilingue', 'Entrée au musée', 'Livret de visite'],
                'pratique'    => ['Niveau' => 'Tous niveaux', 'Distance' => '45 min de Possotomé', 'Durée' => '1 heure environ', 'Groupe' => 'Individuel ou groupe'],
                'highlights'  => ['Fort portugais historique', 'Traite négrière', 'Artéfacts du Dahomey', 'Histoire de l\'esclavage'],
                'icon'        => 'book-open',
                'prev'        => 'temple-pythons',
                'next'        => 'foret-sacree',
            ],
            'foret-sacree' => [
                'slug'        => 'foret-sacree',
                'nom'         => 'Forêt Sacrée',
                'ville'       => 'Ouidah',
                'duree'       => '1 heure',
                'categorie'   => 'Spiritualité & Nature',
                'hero_img'    => 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=1920',
                'galerie'     => [
                    'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800',
                    'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
                    'https://images.unsplash.com/photo-1520209759809-a9bcb6cb3241?w=800',
                ],
                'description' => 'La Forêt Sacrée de Ouidah est un lieu de recueillement et de culte vodoun. Ce bois sacré abrite des divinités et des esprits selon la tradition béninoise. Des statues, autels et sculptures parsèment les sous-bois dans une atmosphère envoûtante et mystérieuse.',
                'details'     => 'La forêt est un sanctuaire vivant où les cérémonies vodoun se déroulent encore régulièrement. Accompagné d\'un guide local initié, vous pénétrerez dans cet espace spirituel unique où chaque arbre, chaque statue raconte une histoire sacrée liée aux divinités du panthéon vodoun.',
                'inclus'      => ['Transport depuis Chez Théo', 'Guide initié', 'Entrée dans la forêt', 'Explications spirituelles'],
                'pratique'    => ['Niveau' => 'Tous niveaux', 'Distance' => '45 min de Possotomé', 'Comportement' => 'Respect absolu requis', 'Photos' => 'Avec autorisation'],
                'highlights'  => ['Ambiance mystique', 'Statues vodoun', 'Cérémonies traditionnelles', 'Nature préservée'],
                'icon'        => 'leaf',
                'prev'        => 'musee-historique',
                'next'        => 'fort-francais',
            ],
            'fort-francais' => [
                'slug'        => 'fort-francais',
                'nom'         => 'Fort Français',
                'ville'       => 'Ouidah',
                'duree'       => '1 heure',
                'categorie'   => 'Histoire & Patrimoine',
                'hero_img'    => 'https://images.unsplash.com/photo-1575223970966-76ae61ee7838?w=1920',
                'galerie'     => [
                    'https://images.unsplash.com/photo-1575223970966-76ae61ee7838?w=800',
                    'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800',
                    'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800',
                ],
                'description' => 'Le Fort Français de Ouidah est l\'un des vestiges les mieux conservés de la présence coloniale européenne sur la côte béninoise. Construit au XVIIe siècle, il fut un point névralgique de la traite négrière transatlantique. Aujourd\'hui musée, il témoigne d\'une période sombre de l\'histoire.',
                'details'     => 'La visite du Fort Français s\'inscrit idéalement dans un circuit Ouidah incluant le Temple des Pythons, la Forêt Sacrée et la Route des Esclaves. Un guide expert vous accompagne pour vous expliquer le rôle de ce fort dans l\'histoire de la traite transatlantique.',
                'inclus'      => ['Transport depuis Chez Théo', 'Guide local expert', 'Entrée au fort', 'Documentation historique'],
                'pratique'    => ['Niveau' => 'Tous niveaux', 'Distance' => '45 min de Possotomé', 'Combinaison' => 'Avec autres sites Ouidah', 'Durée' => '1 heure environ'],
                'highlights'  => ['Architecture coloniale', 'Histoire de la traite', 'Vue panoramique', 'Musée intégré'],
                'icon'        => 'shield',
                'prev'        => 'foret-sacree',
                'next'        => 'centre-artisanal',
            ],
            'centre-artisanal' => [
                'slug'        => 'centre-artisanal',
                'nom'         => 'Centre Artisanal',
                'ville'       => 'Cotonou',
                'duree'       => '1 heure',
                'categorie'   => 'Culture & Artisanat',
                'hero_img'    => 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1920',
                'galerie'     => [
                    'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800',
                    'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800',
                    'https://images.unsplash.com/photo-1520209759809-a9bcb6cb3241?w=800',
                ],
                'description' => 'Le Centre Artisanal de Cotonou est le temple de l\'artisanat béninois. Sculptures en bois, masques traditionnels, bijoux en bronze, textiles tissés à la main, batiks colorés… Tout l\'art et le savoir-faire béninois se retrouvent dans ce lieu incontournable pour rapporter de beaux souvenirs.',
                'details'     => 'Situé dans le cœur de Cotonou, le Centre Artisanal regroupe des dizaines d\'ateliers et boutiques où vous pouvez observer les artisans au travail et acquérir des pièces uniques directement auprès des créateurs. Nos guides vous aident à négocier les meilleurs prix.',
                'inclus'      => ['Transport depuis Chez Théo', 'Guide local', 'Aide à la négociation', 'Sélection des meilleures boutiques'],
                'pratique'    => ['Niveau' => 'Tous niveaux', 'Distance' => '1h30 de Possotomé', 'Budget' => 'Prévoir pour achats', 'Groupe' => '2-10 personnes'],
                'highlights'  => ['Artisans en action', 'Sculptures traditionnelles', 'Textiles colorés', 'Souvenirs authentiques'],
                'icon'        => 'palette',
                'prev'        => 'fort-francais',
                'next'        => 'statue-amazone',
            ],
            'statue-amazone' => [
                'slug'        => 'statue-amazone',
                'nom'         => 'Statue de l\'Amazone',
                'ville'       => 'Cotonou',
                'duree'       => '1 heure',
                'categorie'   => 'Culture & Histoire',
                'hero_img'    => 'https://images.unsplash.com/photo-1575223970966-76ae61ee7838?w=1920',
                'galerie'     => [
                    'https://images.unsplash.com/photo-1575223970966-76ae61ee7838?w=800',
                    'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800',
                    'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800',
                ],
                'description' => 'La Statue de l\'Amazone de Cotonou est l\'un des monuments les plus emblématiques du Bénin. Elle rend hommage aux célèbres guerrières Agojie du royaume du Dahomey, ces femmes soldats redoutables qui défendaient le roi et le royaume. Une figure de fierté et de résistance africaine.',
                'details'     => 'Haute de plusieurs mètres, cette statue imposante domine le boulevard qui porte son nom. La visite est l\'occasion de découvrir l\'histoire extraordinaire des Agojie, ces guerrières qui ont inspiré le film "La femme Roi". Un guide vous racontera leur épopée fascinante.',
                'inclus'      => ['Transport depuis Chez Théo', 'Guide local', 'Histoire des Agojie', 'Photos souvenirs'],
                'pratique'    => ['Niveau' => 'Tous niveaux', 'Distance' => '1h30 de Possotomé', 'Combinaison' => 'Avec Centre Artisanal', 'Durée' => '30-45 minutes'],
                'highlights'  => ['Monument emblématique', 'Guerrières Agojie', 'Histoire du Dahomey', 'Photo iconique'],
                'icon'        => 'sword',
                'prev'        => 'centre-artisanal',
                'next'        => 'memorial-zoungbodji',
            ],
            'memorial-zoungbodji' => [
                'slug'        => 'memorial-zoungbodji',
                'nom'         => 'Mémorial de Zoungbodji',
                'ville'       => 'Ouidah',
                'duree'       => '1 heure',
                'categorie'   => 'Histoire & Mémoire',
                'hero_img'    => 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=1920',
                'galerie'     => [
                    'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800',
                    'https://images.unsplash.com/photo-1575223970966-76ae61ee7838?w=800',
                    'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800',
                ],
                'description' => 'Le Mémorial de Zoungbodji est un lieu de recueillement dédié à la mémoire des victimes de la traite négrière transatlantique. Situé à Ouidah, il marque l\'emplacement du marché aux esclaves et constitue un lieu de mémoire essentiel pour comprendre cette page douloureuse de l\'histoire.',
                'details'     => 'Le Mémorial se trouve sur la Route des Esclaves, qui mène de Ouidah à la mer. La visite est profondément émouvante et éducative. Elle s\'inscrit dans un parcours mémoriel qui inclut la Porte du Non-Retour et les différents forts de Ouidah.',
                'inclus'      => ['Transport depuis Chez Théo', 'Guide local expert', 'Entrée au mémorial', 'Contexte historique complet'],
                'pratique'    => ['Niveau' => 'Tous niveaux', 'Distance' => '45 min de Possotomé', 'Ambiance' => 'Lieu de mémoire solennel', 'Combinaison' => 'Route des Esclaves'],
                'highlights'  => ['Lieu de mémoire', 'Route des Esclaves', 'Porte du Non-Retour', 'Histoire de la traite'],
                'icon'        => 'heart',
                'prev'        => 'statue-amazone',
                'next'        => 'refuge-tortues',
            ],
            'refuge-tortues' => [
                'slug'        => 'refuge-tortues',
                'nom'         => 'Refuge des Tortues Marines',
                'ville'       => 'Agbanakin',
                'duree'       => '1 heure',
                'categorie'   => 'Nature & Écologie',
                'hero_img'    => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1920',
                'galerie'     => [
                    'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
                    'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800',
                    'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=800',
                ],
                'description' => 'Le Refuge des Tortues Marines d\'Agbanakin est un centre de conservation qui protège les tortues marines menacées sur les côtes béninoises. Vous pourrez observer ces magnifiques reptiles, découvrir le processus de ponte et d\'éclosion et comprendre les enjeux de leur préservation.',
                'details'     => 'Ce refuge unique en son genre recueille et protège les œufs de tortues marines, notamment les tortues olivâtres. Les responsables du refuge vous expliqueront leur mission de conservation et le fragile équilibre écologique du littoral béninois. Une expérience rare et émouvante.',
                'inclus'      => ['Transport depuis Chez Théo', 'Guide naturaliste', 'Entrée au refuge', 'Explications sur la conservation'],
                'pratique'    => ['Niveau' => 'Tous niveaux', 'Distance' => '1h de Possotomé', 'Saison' => 'Toute l\'année', 'Groupe' => '2-15 personnes'],
                'highlights'  => ['Tortues marines protégées', 'Écloserie d\'œufs', 'Conservation marine', 'Plage naturelle'],
                'icon'        => 'shield',
                'prev'        => 'memorial-zoungbodji',
                'next'        => null,
            ],
        ];
    }

    public function index()
    {
        return view('pages.excursions', ['excursions' => $this->getData()]);
    }

    public function show($slug)
    {
        $data = $this->getData();
        if (!isset($data[$slug])) {
            abort(404);
        }
        $e    = $data[$slug];
        $prev = $e['prev'] ? $data[$e['prev']] : null;
        $next = $e['next'] ? $data[$e['next']] : null;
        $all  = array_values($data);
        return view('pages.excursion-detail', compact('e', 'prev', 'next', 'all'));
    }
}
